# Generated by roxytest: Do not edit by hand!

# File R/REGModel.R: @testexamples

test_that("Function REGModel() @ L21", {
  
  library(survival)
  test1 <- data.frame(
    time = c(4, 3, 1, 1, 2, 2, 3),
    status = c(1, 1, 1, 0, 1, 1, 0),
    x = c(0, 2, 1, 1, 1, 0, 0),
    sex = c(0, 0, 0, 0, 1, 1, 1)
  )
  mm <- REGModel$new(as.data.frame(test1), Surv(time, status) ~ x + strata(sex), f = survival::coxph)
  mm
  as.data.frame(mm$result)
  expect_is(mm, "REGModel")
})

