# Generated by roxytest: Do not edit by hand!

# File R/REGModelList.R: @testexamples

test_that("Function REGModelList() @ L24", {
  
  ml <- REGModelList$new(
    data = mtcars,
    y = "mpg",
    x = c("factor(cyl)", colnames(mtcars)[3:5]),
    covars = c(colnames(mtcars)[8:9], "factor(gear)")
  )
  ml
  ml$build(f = "gaussian")
  ml$result
  ml$forest_data
  
  ml$plot_forest(ref_line = 0, xlim = c(-15, 8))
  expect_is(ml, "REGModelList")
})

