# Generated by roxytest: Do not edit by hand!

# File R/REGModelList.R: @testexamples

test_that("Function REGModelList() @ L28", {
  
  ml <- REGModelList$new(
    data = mtcars,
    y = "mpg",
    x = c("factor(cyl)", colnames(mtcars)[3:5]),
    covars = c(colnames(mtcars)[8:9], "factor(gear)")
  )
  ml
  ml$print()
  ml$plot_forest()
  
  ml$build(f = "gaussian")
  ml$build(f = "gaussian", parallel = TRUE)
  ml$print()
  ml$result
  ml$forest_data
  ml$plot_forest()
  expect_is(ml, "REGModelList")
})

